"use client";

import { useState, useEffect } from "react";
import {
  Monitor, Tablet, Smartphone, RefreshCw,
  Download, Loader2, CheckCircle2, AlertCircle,
  Check, Palette, ExternalLink,
} from "lucide-react";
import { usePortfolioConfig } from "@/hooks/use-portfolio-config";
import { useGitHubData } from "@/hooks/use-github-data";
import { TEMPLATE_DEFINITIONS } from "@/types/portfolio";
import type { TemplateId } from "@/types/portfolio";
import { cn } from "@/lib/utils";

const deviceSizes = {
  desktop: { width: "100%",  icon: Monitor  },
  tablet:  { width: "768px", icon: Tablet   },
  mobile:  { width: "375px", icon: Smartphone },
} as const;

type DeviceType = keyof typeof deviceSizes;

export default function LaunchPage() {
  const { config, patch, save } = usePortfolioConfig();
  const { isLoading: ghLoading } = useGitHubData();

  const [device,           setDevice]           = useState<DeviceType>("desktop");
  const [previewHtml,      setPreviewHtml]      = useState<string | null>(null);
  const [generating,       setGenerating]       = useState(false);
  const [genError,         setGenError]         = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [dlSuccess,        setDlSuccess]        = useState(false);
  const [dlError,          setDlError]          = useState<string | null>(null);

  const activeTemplate = config?.settings?.activeTemplate ?? "minimalist";
  const activeTmpl     = TEMPLATE_DEFINITIONS.find((t) => t.id === activeTemplate);

  /* ─── Generate preview ─────────────────────── */
  const generate = async () => {
    if (!config) return;
    setGenerating(true);
    setGenError(null);
    try {
      const res  = await fetch("/api/portfolio/generate", { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify(config) });
      const text = await res.text();
      let result: { files?: { path: string; content: string }[]; error?: string };
      try { result = JSON.parse(text); }
      catch {
        if (text.includes("<!DOCTYPE") || text.includes("<html")) throw new Error("Session expired — please sign in again.");
        throw new Error(`Unexpected server response (${res.status})`);
      }
      if (!res.ok) throw new Error(result.error || `Server error ${res.status}`);
      const htmlFile = result.files?.find((f) => f.path === "index.html");
      if (htmlFile) setPreviewHtml(htmlFile.content);
      else throw new Error("No index.html in generated output");
    } catch (err) {
      setGenError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setGenerating(false);
    }
  };

  useEffect(() => {
    if (config && !hasAutoGenerated && !ghLoading) {
      setHasAutoGenerated(true);
      generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [config, ghLoading]);

  /* ─── Switch template + re-generate ──────────── */
  const switchTemplate = async (id: TemplateId) => {
    if (!config) return;
    patch("settings", { ...config.settings, activeTemplate: id });
    await save();
    setTimeout(generate, 150);
  };

  /* ─── Download via form POST → new tab ──────── */
  const handleDownload = () => {
    if (!config) return;
    setDlError(null);

    try {
      /*
       * POST to /api/portfolio/download in a NEW TAB (target="_blank").
       * The server responds with Content-Disposition: attachment; filename="…"
       * The browser downloads the file with the correct name from the header.
       *
       * Why this works when blob/data URLs don't:
       * - It's a real HTTP response, not a JavaScript-constructed URL
       * - The browser's native download manager reads Content-Disposition
       * - No blob UUID, no data: URL security block, no async gesture loss
       */
      const form = document.createElement("form");
      form.method = "POST";
      form.action = "/api/portfolio/download";
      form.target = "_blank";           // open in new tab → stays on this page
      form.style.display = "none";

      const input = document.createElement("input");
      input.type  = "hidden";
      input.name  = "config";
      input.value = JSON.stringify(config);
      form.appendChild(input);

      document.body.appendChild(form);
      form.submit();                    // synchronous native browser action
      document.body.removeChild(form);

      setDlSuccess(true);
      setTimeout(() => setDlSuccess(false), 5000);
    } catch (err: unknown) {
      setDlError(err instanceof Error ? err.message : String(err));
    }
  };

  /* ─── Open full portfolio in new tab ─────────── */
  const handleOpen = () => {
    if (!previewHtml) return;
    const blob = new Blob([previewHtml], { type: "text/html;charset=utf-8" });
    const url  = URL.createObjectURL(blob);
    const win  = window.open(url, "_blank", "noopener,noreferrer");
    if (win) setTimeout(() => URL.revokeObjectURL(url), 30_000);
  };

  /* ─── Loading skeleton ─────────────────────── */
  if (!config || ghLoading) {
    return (
      <div className="space-y-5 animate-pulse">
        <div className="h-8  w-48 bg-[#1c1b1b] rounded-lg" />
        <div className="h-14 w-full bg-[#1c1b1b] rounded-xl" />
        <div className="h-[600px] bg-[#1c1b1b] rounded-xl" />
      </div>
    );
  }

  return (
    <div className="space-y-5 max-w-6xl">

      {/* ── Header row ──────────────────────────── */}
      <div className="flex items-end justify-between gap-4">
        <div>
          <p className="font-label text-[10px] uppercase tracking-widest text-[#8b90a0] mb-1">
            Step 2 · Launch
          </p>
          <h1 className="font-headline font-extrabold text-3xl tracking-tight text-[#e5e2e1]">
            Preview & Download
          </h1>
          <p className="text-[#8b90a0] text-sm mt-1">
            Pick a template, preview your site, then download the HTML file.
          </p>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2 shrink-0">
          {/* Device toggles */}
          <div className="flex items-center bg-[#1c1b1b] border border-[#414754]/20 rounded-lg p-1">
            {(Object.entries(deviceSizes) as [DeviceType, (typeof deviceSizes)[DeviceType]][]).map(([key, info]) => (
              <button key={key} onClick={() => setDevice(key)} className={cn("w-8 h-8 flex items-center justify-center rounded-md transition-all", device === key ? "bg-[#2a2a2a] text-[#aec6ff]" : "text-[#8b90a0] hover:text-[#e5e2e1]")}>
                <info.icon className="w-4 h-4" />
              </button>
            ))}
          </div>

          {/* Refresh */}
          <button onClick={generate} disabled={generating} className="flex items-center gap-1.5 px-3 py-2 bg-[#1c1b1b] border border-[#414754]/20 text-sm font-label text-[#e5e2e1] rounded-lg hover:bg-[#2a2a2a] disabled:opacity-50 transition-all">
            <RefreshCw className={cn("w-4 h-4", generating && "animate-spin")} />
            {previewHtml ? "Refresh" : "Generate"}
          </button>

          {/* Open in new tab */}
          {previewHtml && (
            <button
              onClick={handleOpen}
              title="Open portfolio in a new browser tab"
              className="flex items-center gap-1.5 px-3 py-2 bg-[#1c1b1b] border border-[#414754]/20 text-sm font-label text-[#e5e2e1] rounded-lg hover:bg-[#2a2a2a] transition-all"
            >
              <ExternalLink className="w-4 h-4" />
              Open
            </button>
          )}

          {/* Download */}
          <button
            onClick={handleDownload}
            disabled={!config}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-lg font-headline font-bold text-sm shadow-lg transition-all active:scale-[0.98] disabled:opacity-50",
              dlSuccess
                ? "bg-[#4edea3]/10 border border-[#4edea3]/30 text-[#4edea3]"
                : "bg-gradient-to-r from-[#aec6ff] to-[#0070f3] text-[#002e6b] shadow-blue-500/15 hover:shadow-blue-500/30"
            )}
          >
            {dlSuccess ? (
              <><CheckCircle2 className="w-4 h-4" /> Downloaded!</>
            ) : generating && !previewHtml ? (
              <><Loader2 className="w-4 h-4 animate-spin" /> Generating…</>
            ) : (
              <><Download className="w-4 h-4" /> Download HTML</>
            )}
          </button>
        </div>
      </div>

      {/* ── Error banners ────────────────────────── */}
      {dlError && (
        <div className="flex items-start gap-3 p-4 bg-[#ffb4ab]/10 border border-[#ffb4ab]/20 rounded-xl">
          <AlertCircle className="w-4 h-4 text-[#ffb4ab] mt-0.5 shrink-0" />
          <p className="text-sm text-[#ffb4ab]/80 font-mono">{dlError}</p>
        </div>
      )}

      {/* ── Template strip ───────────────────────── */}
      <div className="bg-[#1c1b1b] border border-[#414754]/15 rounded-xl p-4">
        <div className="flex items-center gap-2 mb-3">
          <Palette className="w-3.5 h-3.5 text-[#8b90a0]" />
          <span className="font-label text-[10px] uppercase tracking-widest text-[#8b90a0]">
            Choose Template
          </span>
        </div>
        <div className="flex flex-wrap gap-2">
          {TEMPLATE_DEFINITIONS.map((tmpl) => {
            const isActive = activeTemplate === tmpl.id;
            return (
              <button
                key={tmpl.id}
                onClick={() => switchTemplate(tmpl.id as TemplateId)}
                className={cn(
                  "flex items-center gap-2 px-3 py-2 rounded-lg border font-label text-xs font-medium transition-all",
                  isActive
                    ? "border-[#aec6ff]/40 bg-[#aec6ff]/10 text-[#aec6ff]"
                    : "border-[#414754]/20 text-[#8b90a0] hover:border-[#414754]/50 hover:text-[#e5e2e1]"
                )}
              >
                <span className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: tmpl.accentColor }} />
                {tmpl.name}
                {isActive && <Check className="w-3 h-3 ml-0.5" />}
              </button>
            );
          })}
        </div>
      </div>

      {/* ── Meta badges ──────────────────────────── */}
      <div className="flex items-center gap-2 flex-wrap">
        {[
          { label: activeTmpl?.name ?? activeTemplate, dot: activeTmpl?.accentColor },
          { label: `${config.projects.length} projects` },
          { label: `${config.skills.length} skills` },
          { label: `${config.experience.length} experience` },
        ].map((b, i) => (
          <span key={i} className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#1c1b1b] border border-[#414754]/20 font-label text-[10px] uppercase tracking-wider text-[#8b90a0]">
            {b.dot && <span className="w-2 h-2 rounded-full" style={{ backgroundColor: b.dot }} />}
            {b.label}
          </span>
        ))}
      </div>

      {/* ── Preview frame ────────────────────────── */}
      <div className="bg-[#1c1b1b] border border-[#414754]/15 rounded-xl overflow-hidden">
        <div className="mx-auto transition-all duration-300" style={{ width: deviceSizes[device].width, maxWidth: "100%" }}>
          {previewHtml ? (
            <iframe srcDoc={previewHtml} className="w-full border-0" style={{ height: "720px" }} title="Portfolio Preview" sandbox="allow-same-origin allow-scripts" />
          ) : (
            <div className="flex items-center justify-center h-[720px]">
              <div className="text-center space-y-5 max-w-sm px-6">
                {generating ? (
                  <>
                    <div className="w-16 h-16 rounded-2xl bg-[#aec6ff]/10 flex items-center justify-center mx-auto">
                      <RefreshCw className="w-8 h-8 text-[#aec6ff] animate-spin" />
                    </div>
                    <div>
                      <p className="font-headline font-bold text-[#e5e2e1]">Generating your portfolio…</p>
                      <p className="text-xs text-[#8b90a0] mt-1">This takes a few seconds</p>
                    </div>
                  </>
                ) : genError ? (
                  <>
                    <div className="p-4 bg-[#ffb4ab]/10 border border-[#ffb4ab]/20 rounded-xl text-left">
                      <p className="text-sm font-headline font-bold text-[#ffb4ab] mb-1">Generation failed</p>
                      <p className="text-xs text-[#ffb4ab]/70 font-mono break-all">{genError}</p>
                    </div>
                    <button onClick={generate} className="flex items-center gap-2 bg-[#ffb4ab]/10 border border-[#ffb4ab]/20 text-[#ffb4ab] px-4 py-2 rounded-lg text-sm font-label font-medium mx-auto hover:bg-[#ffb4ab]/20 transition-colors">
                      <RefreshCw className="w-4 h-4" /> Retry
                    </button>
                  </>
                ) : (
                  <>
                    <div className="w-16 h-16 rounded-2xl bg-[#2a2a2a] flex items-center justify-center mx-auto">
                      <Monitor className="w-8 h-8 text-[#414754]" />
                    </div>
                    <div>
                      <p className="font-headline font-bold text-[#e5e2e1]">No preview yet</p>
                      <p className="text-sm text-[#8b90a0] mt-1">Click &quot;Generate&quot; to see your portfolio live</p>
                    </div>
                    <button onClick={generate} className="flex items-center gap-2 bg-[#aec6ff] text-[#002e6b] font-headline font-bold px-5 py-2.5 rounded-lg mx-auto shadow-lg shadow-blue-500/15 hover:opacity-90 transition-opacity">
                      <RefreshCw className="w-4 h-4" /> Generate Preview
                    </button>
                  </>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── Download CTA (only after preview is ready) ── */}
      {previewHtml && (
        <div className="flex items-center gap-4 p-5 bg-[#1c1b1b] border border-[#414754]/15 rounded-xl">
          <div className="flex-1">
            <p className="font-headline font-bold text-[#e5e2e1]">Ready to ship?</p>
            <p className="text-xs text-[#8b90a0] mt-0.5">
              Download a single HTML file — open directly in any browser, or drop it onto Netlify, GitHub Pages, or any CDN.
            </p>
          </div>
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 bg-gradient-to-r from-[#aec6ff] to-[#0070f3] text-[#002e6b] font-headline font-bold px-6 py-2.5 rounded-lg shadow-lg shadow-blue-500/15 hover:shadow-blue-500/30 active:scale-[0.99] transition-all shrink-0"
          >
            <Download className="w-4 h-4" /> Download HTML
          </button>
        </div>
      )}
    </div>
  );
}
