"use client";

import { useState, useEffect } from "react";
import { Monitor, Tablet, Smartphone, RefreshCw, Palette, ExternalLink } from "lucide-react";
import { usePortfolioConfig } from "@/hooks/use-portfolio-config";
import { useGitHubData } from "@/hooks/use-github-data";
import { TEMPLATE_DEFINITIONS } from "@/types/portfolio";
import type { TemplateId } from "@/types/portfolio";
import { cn } from "@/lib/utils";
import Link from "next/link";

const deviceSizes = {
  desktop: { width: "100%",  label: "Desktop", icon: Monitor },
  tablet:  { width: "768px", label: "Tablet",  icon: Tablet },
  mobile:  { width: "375px", label: "Mobile",  icon: Smartphone },
};

type DeviceType = keyof typeof deviceSizes;

export default function PreviewPage() {
  const { config, patch } = usePortfolioConfig();
  const { isLoading: ghLoading } = useGitHubData();
  const [device, setDevice] = useState<DeviceType>("desktop");
  const [previewHtml, setPreviewHtml] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const activeTemplate = config?.settings?.activeTemplate ?? "minimalist";

  const generatePreview = async () => {
    if (!config) return;
    setGenerating(true);
    setError(null);
    try {
      const res = await fetch("/api/portfolio/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(config),
      });
      const text = await res.text();
      let result: { files?: { path: string; content: string }[]; error?: string };
      try {
        result = JSON.parse(text);
      } catch {
        if (text.includes("<!DOCTYPE") || text.includes("<html")) {
          throw new Error("Session expired — please sign out and sign in again.");
        }
        throw new Error(`Unexpected server response (${res.status})`);
      }
      if (!res.ok) throw new Error(result.error || `Server error ${res.status}`);
      const htmlFile = result.files?.find((f) => f.path === "index.html");
      if (htmlFile) setPreviewHtml(htmlFile.content);
      else throw new Error("No index.html in generated output");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setGenerating(false);
    }
  };

  useEffect(() => {
    if (config && !hasAutoGenerated && !ghLoading) {
      setHasAutoGenerated(true);
      generatePreview();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [config, ghLoading]);

  const switchTemplate = async (id: TemplateId) => {
    if (!config) return;
    patch("settings", { ...config.settings, activeTemplate: id });
    setTimeout(generatePreview, 100);
  };

  if (ghLoading || !config) {
    return (
      <div className="space-y-5 animate-pulse">
        <div className="h-8 w-48 bg-[#1c1b1b] rounded-lg" />
        <div className="h-12 w-full bg-[#1c1b1b] rounded-xl" />
        <div className="h-[600px] bg-[#1c1b1b] rounded-xl" />
      </div>
    );
  }

  const activeTmpl = TEMPLATE_DEFINITIONS.find((t) => t.id === activeTemplate);

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="font-label text-[10px] uppercase tracking-widest text-[#8b90a0]">
              Dashboard · Preview
            </span>
          </div>
          <h1 className="font-headline font-extrabold text-3xl tracking-tight text-[#e5e2e1]">
            Live Preview
          </h1>
          <p className="text-[#8b90a0] mt-1 text-sm">
            See exactly how your portfolio will look — switch templates instantly.
          </p>
        </div>

        {/* Device + Refresh controls */}
        <div className="flex items-center gap-2">
          <div className="flex items-center bg-[#1c1b1b] border border-[#414754]/20 rounded-lg p-1">
            {(Object.entries(deviceSizes) as [DeviceType, (typeof deviceSizes)[DeviceType]][]).map(
              ([key, info]) => (
                <button
                  key={key}
                  onClick={() => setDevice(key)}
                  title={info.label}
                  className={cn(
                    "w-8 h-8 flex items-center justify-center rounded-md transition-all",
                    device === key
                      ? "bg-[#2a2a2a] text-[#aec6ff]"
                      : "text-[#8b90a0] hover:text-[#e5e2e1]"
                  )}
                >
                  <info.icon className="w-4 h-4" />
                </button>
              )
            )}
          </div>

          <button
            onClick={generatePreview}
            disabled={generating}
            className="flex items-center gap-2 bg-[#1c1b1b] border border-[#414754]/20 text-[#e5e2e1] hover:bg-[#2a2a2a] px-4 py-2 rounded-lg text-sm font-label font-medium transition-all disabled:opacity-50"
          >
            <RefreshCw className={cn("w-4 h-4", generating && "animate-spin")} />
            {previewHtml ? "Refresh" : "Generate Preview"}
          </button>
        </div>
      </div>

      {/* Template switcher */}
      <div className="bg-[#1c1b1b] border border-[#414754]/15 rounded-xl p-4">
        <div className="flex items-center gap-2 mb-3">
          <Palette className="w-3.5 h-3.5 text-[#8b90a0]" />
          <span className="font-label text-[10px] uppercase tracking-widest text-[#8b90a0]">
            Switch Template
          </span>
        </div>
        <div className="flex flex-wrap gap-2">
          {TEMPLATE_DEFINITIONS.map((tmpl) => (
            <button
              key={tmpl.id}
              onClick={() => switchTemplate(tmpl.id as TemplateId)}
              className={cn(
                "flex items-center gap-2 px-3 py-1.5 rounded-lg border font-label text-xs font-medium transition-all",
                activeTemplate === tmpl.id
                  ? "border-[#aec6ff]/40 bg-[#aec6ff]/10 text-[#aec6ff]"
                  : "border-[#414754]/20 text-[#8b90a0] hover:border-[#414754]/50 hover:text-[#e5e2e1]"
              )}
            >
              <span className="w-2 h-2 rounded-full" style={{ backgroundColor: tmpl.accentColor }} />
              {tmpl.name}
            </button>
          ))}
        </div>
      </div>

      {/* Meta badges */}
      <div className="flex items-center gap-2 flex-wrap">
        {[
          { label: activeTmpl?.name ?? activeTemplate, dot: activeTmpl?.accentColor },
          { label: `${config.projects.length} projects` },
          { label: `${config.skills.length} skills` },
          { label: `${config.experience.length} experience` },
        ].map((b, i) => (
          <span
            key={i}
            className="flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#1c1b1b] border border-[#414754]/20 font-label text-[10px] uppercase tracking-wider text-[#8b90a0]"
          >
            {b.dot && <span className="w-2 h-2 rounded-full" style={{ backgroundColor: b.dot }} />}
            {b.label}
          </span>
        ))}
      </div>

      {/* Preview frame */}
      <div className="bg-[#1c1b1b] border border-[#414754]/15 rounded-xl overflow-hidden">
        <div
          className="mx-auto transition-all duration-300"
          style={{ width: deviceSizes[device].width, maxWidth: "100%" }}
        >
          {previewHtml ? (
            <iframe
              srcDoc={previewHtml}
              className="w-full border-0"
              style={{ height: "750px" }}
              title="Portfolio Preview"
              sandbox="allow-same-origin allow-scripts"
            />
          ) : (
            <div className="flex items-center justify-center h-[750px]">
              <div className="text-center space-y-5 max-w-sm px-4">
                {generating ? (
                  <>
                    <div className="w-16 h-16 rounded-2xl bg-[#aec6ff]/10 flex items-center justify-center mx-auto">
                      <RefreshCw className="w-8 h-8 text-[#aec6ff] animate-spin" />
                    </div>
                    <p className="font-headline font-bold text-[#e5e2e1]">
                      Generating your portfolio…
                    </p>
                    <p className="text-xs text-[#8b90a0]">This takes a moment</p>
                  </>
                ) : error ? (
                  <>
                    <div className="p-4 bg-[#ffb4ab]/10 border border-[#ffb4ab]/20 rounded-xl text-left">
                      <p className="text-sm font-headline font-bold text-[#ffb4ab] mb-1">
                        Generation failed
                      </p>
                      <p className="text-xs text-[#ffb4ab]/70 font-mono break-all">{error}</p>
                    </div>
                    <button
                      onClick={generatePreview}
                      disabled={generating}
                      className="flex items-center gap-2 bg-[#ffb4ab]/10 border border-[#ffb4ab]/20 text-[#ffb4ab] px-4 py-2 rounded-lg text-sm font-label font-medium mx-auto hover:bg-[#ffb4ab]/20 transition-colors"
                    >
                      <RefreshCw className="w-4 h-4" /> Retry
                    </button>
                  </>
                ) : (
                  <>
                    <div className="w-16 h-16 rounded-2xl bg-[#2a2a2a] flex items-center justify-center mx-auto">
                      <Monitor className="w-8 h-8 text-[#414754]" />
                    </div>
                    <div>
                      <p className="font-headline font-bold text-[#e5e2e1]">No preview yet</p>
                      <p className="text-sm text-[#8b90a0] mt-1">
                        Click &quot;Generate Preview&quot; to see your portfolio live
                      </p>
                    </div>
                    <button
                      onClick={generatePreview}
                      className="flex items-center gap-2 bg-[#aec6ff] text-[#002e6b] font-headline font-bold px-5 py-2.5 rounded-lg mx-auto shadow-lg shadow-blue-500/15 hover:opacity-90 transition-opacity"
                    >
                      <RefreshCw className="w-4 h-4" /> Generate Preview
                    </button>
                  </>
                )}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Footer hint */}
      {previewHtml && (
        <div className="flex items-center gap-2 text-xs text-[#8b90a0] font-label">
          <ExternalLink className="w-3.5 h-3.5" />
          <span>
            Ready to ship? Go to the{" "}
            <Link href="/dashboard/deploy" className="text-[#aec6ff] underline underline-offset-4 hover:opacity-80">
              Deploy
            </Link>{" "}
            page to download your site.
          </span>
        </div>
      )}
    </div>
  );
}
